---
image: node:10.16.3-jessie

variables:
  NODE_VERSION: "10.16.3"

stages:
  - test
  - build
  - deploy

# ----------------------------------
# TEST
# ----------------------------------

test app:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm install
    - npm run test:ci

# ----------------------------------
# BUILD
# ----------------------------------

build app:
  only:
    - master
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm install
    - npm run build
  only:
    - master

# ----------------------------------
# DEPLOY TO STAGING
# ----------------------------------

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - npm install
    - npm run build
  environment:
    name: staging
  when: manual
  only:
    - master
