---
image: node:10.16.3-jessie

variables:
  NODE_VERSION: "10.16.3"

stages:
  - test
  - build

# ----------------------------------
# TEST
# ----------------------------------

test app:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm install
    - npm run test:ci

# ----------------------------------
# BUILD
# ----------------------------------

build app:
  only:
    - master
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm install
    - npm run build
